FROM        python:3.6.4-slim

RUN         apt-get -y update
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install nginx supervisor
RUN         apt-get -y install build-essential

COPY        .requirements /srv/hackathon/.requirements
WORKDIR     /srv/hackathon
RUN         pip install --upgrade pip &&\
            pip install -r .requirements/requirements_production.txt


